version: '3.8'

services:
  django:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:9900
    volumes:
      - .:/app
    ports:
      - "9900:9900"
    depends_on:
      - postgres
      - redis
    environment:
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_USER=$POSTGRES_USER
      - REDIS_HOST=redis
      - CELERY_BROKER_REDIS_URL=CELERY_BROKER_REDIS_URL

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    
  # celery_worker:
  #   build: .
  #   command: celery -A core worker --beat -l INFO
  #   depends_on:
  #     - django
  #     - redis
  #   environment:
  #     - REDIS_HOST=redis

volumes:  
  pgdata: {}